defaults:
  - _self_
  - model: tinyhar
  - dataset: har_dataset

# Training Hyperparameters
epochs: 1
batch_size: 250
lr: 0.0001
weight_decay: 0.0001
patience: 20
aux_weight: 0.4

# Experiment Settings
results_dir: "results"
seed: 42
limit_folds: 1
resume_dir: null
